### ISSUE TITLE
Add a CKAN instance to docker compose for testing

### ISSUE THREAD

**Issue by avdata99** [datopian/ckan-ng-harvest#3]
Based on [ckan-multi#195](https://github.com/GSA/datagov-ckan-multi/issues/195).

It is useful to be able to test harvesting jobs manually, on a local machine. In order to support this, the new harvesters need to ship a docker compose configuration that not only sets up a running harvester, but also a running CKAN configured and ready for use as a target for the data that is harvested.

* [x] Define the best CKAN container ([docker-ckan is a good idea](https://github.com/okfn/docker-ckan))
* [x] Implement it

# Acceptance criteria
- [ ] Document a Docker Compose command that will set up the harvester dependencies, *and*, CKAN and its dependencies
  - This may require additional configuration and code to support the smooth operation of this local environment
- [ ] Verify that GSA team can follow the instructions and run the datajson harvester.

**Comment by kimwdavidson** [comment]
duplicate #195. closing
